FROM node:16-alpine as builder 
WORKDIR /var/www/clientapp_frontend 
COPY package.json .
RUN npm install
COPY . .
# two lines below to make FLASK_API_URL settable via --build-arg in docker build command
ARG BUILDTIME_FLASK_API_URL='some_fallback_default_URL'
ENV FLASK_API_URL=$BUILDTIME_FLASK_API
RUN npm run build

# taking the dist build from the previous builder container and using it in a nginx container
FROM nginx:1.17-alpine
COPY — from=builder /var/www/clientapp_frontend/build/ /usr/share/nginx/html
COPY — from=builder /var/www/clientapp_frontend/nginx_entrypoint.sh ./nginx_entrypoint.sh
EXPOSE $FRONTEND_PORT
ENTRYPOINT /bin/sh -x ./nginx_entrypoint.sh && nginx -g ‘daemon off;’